#!/usr/bin/python
#
# Copyright (c) 2011 Bogdano Arendartchuk <bogdano@mandriva.com.br>
#
# Written by Bogdano Arendartchuk <bogdano@mandriva.com.br>
#
# This file is part of Jurt Build Bot.
#
# Jurt Build Bot is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# Jurt Build Bot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Jurt Build Bot; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
from jurtlib.command import JurtCommand, CliError

DESCR = """\
Lists roots available to be used on jurt-shell -i <ID>

The output is in the format TYPE LATEST NAME.

TYPE can be:

 b      indicates that it was used for non-interactive build (and thus
        can only be reused for that purpuse)
 i      it can be used for interactive build or shell (jurt-build -b or
        jurt-shell)

LATEST points if the root can be referred with -l on the commands that
support this option.
"""

class ListRoots(JurtCommand):

    descr = DESCR

    def init_parser(self, parser):
        JurtCommand.init_parser(self, parser)

    def run(self):
        for name, kind, latest in self.jurt.list_roots():
            print "%s %s\t%s" % (kind[0], ("", "*")[latest], name)

ListRoots().main()
