#!/usr/bin/python
#
# Copyright (c) 2011 Bogdano Arendartchuk <bogdano@mandriva.com.br>
#
# Written by Bogdano Arendartchuk <bogdano@mandriva.com.br>
#
# This file is part of Jurt Build Bot.
#
# Jurt Build Bot is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# Jurt Build Bot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Jurt Build Bot; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
from jurtlib.command import JurtCommand, CliError

DESCR = """\
Creates a root and drops into a shell.

(Notice you can also use jurt-build --stop)
"""

class Shell(JurtCommand):

    usage = "%prog -t TARGET [-l] [-i|-n root-id]"
    descr = DESCR

    def init_parser(self, parser):
        JurtCommand.init_parser(self, parser)
        parser.add_option("-t", "--target", type="string",
                help="Target root name (jurt-list-targets for a list)")
        parser.add_option("-i", "--id", default=None,
                help=("Enter in an (supposedly) existing root named "
                    "ID (see -l)"))
        parser.add_option("-l", "--latest", default=False,
                action="store_true",
                help="Use the latest created root")
        parser.add_option("-n", "--newid", default=None, metavar="ID",
                help=("Set the name of the root to be created "
                    "(so that it can be reused with -i ID)"))

    def run(self):
        if sum((self.opts.latest, bool(self.opts.id),
                bool(self.opts.newid))) > 1:
            raise CliError, "-i, -n and -l cannot be used together"
        fresh = True
        id = None
        if self.opts.id:
            fresh = False
            id = self.opts.id
        if self.opts.latest:
            id = "latest"
            fresh = False
        elif self.opts.newid:
            id = self.opts.newid
        # else: fresh = True
        self.jurt.shell(self.opts.target, id, fresh)

Shell().main()
