#!/usr/bin/python
from jurtlib.command import JurtCommand, CliError

DESCR = """\
Creates a root and drops into a shell.

(Notice you can also use jurt-build --stop)
"""

class Shell(JurtCommand):

    usage = "%prog -t TARGET [-l] [-i|-n root-id]"
    descr = DESCR

    def init_parser(self, parser):
        JurtCommand.init_parser(self, parser)
        parser.add_option("-t", "--target", type="string",
                help="Target rooot name (jurt-list-targets for a list)")
        parser.add_option("-i", "--id", default=None,
                help=("Enter in an (supposedly) existing root named "
                    "ID (see -l)"))
        parser.add_option("-l", "--latest", default=False,
                action="store_true",
                help="Use the latest created root")
        parser.add_option("-n", "--newid", default=None, metavar="ID",
                help=("Set the name of the root to be created "
                    "(so that it can be reused with -i ID)"))

    def run(self):
        if sum((self.opts.latest, bool(self.opts.id),
                bool(self.opts.newid))) > 1:
            raise CliError, "-i, -n and -l cannot be used together"
        fresh = True
        id = None
        if self.opts.id:
            fresh = False
            id = self.opts.id
        if self.opts.latest:
            id = "latest"
            fresh = False
        elif self.opts.newid:
            id = self.opts.newid
        # else: fresh = True
        self.jurt.shell(self.opts.target, id, fresh)

Shell().main()
